src/lottery/urls.py
from django.urls import path

from lottery.views.home import HomeView
from lottery.views.tickets import (
    AcceptBuyTicketNotice, BuyTicketView)
from lottery.views.bets import BetsListView
from lottery.views.lotteries import (
    LotteryListView, LotteryDetailView)
from lottery.views.about import AboutView
from lottery.views.schedule import ScheduleView
from lottery.views.faq import FAQView

app_name = 'lottery'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('buy-ticket/', BuyTicketView.as_view(), name='buy-ticket'),
    path('accept-buy-ticket-notice/', AcceptBuyTicketNotice.as_view(), name='accept-notice'),
    path('bets/', BetsListView.as_view(), name='bet-list'),
    path('lotteries/', LotteryListView.as_view(), name='lottery-list'),
    path('lotteries/<int:pk>/', LotteryDetailView.as_view(), name='lottery-detail'),
    path('schedule/', ScheduleView.as_view(), name='schedule'),
    path('faq/', FAQView.as_view(), name='faq'),
    path('about/', AboutView.as_view(), name='about')
]

src/luckyfive/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('lottery.urls')),
    path('admin/', admin.site.urls),
]

src/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Lucky Five</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    {% block head %}{% endblock %}
</head>
<body>
    {% include 'navbar.html' %}

    <div class="content">
        {% block content %} {% endblock %}
    </div>

    {% include 'footer.html' %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    {% block script %}
    {% endblock %}
</body>
</html>

src/templates/footer.html
<nav class="navbar fixed-bottom navbar-dark navbar-expand-lg">
    <div class="container-fluid justify-content-center">
        <span class="navbar-text">
            © LuckyFive 2021
        </span>
    </div>
</nav>

src/templates/navbar.html
{% load static %}

<nav class="navbar fixed-top navbar-dark navbar-expand-lg">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'lottery:home' %}">
            <img 
                src="{% static 'images/LuckyFive.png' %}"
                alt="" width="35" height="35"
                class="d-inline-block align-text-center"
            >
            LuckyFive
        </a>
        <button 
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <div class="navbar-nav ms-auto">
                {% if request.path == "/buy-ticket/" %}
                    <a class="nav-link active" href="{% url 'lottery:buy-ticket' %}">Buy Ticket</a>
                {% else %}
                    <a class="nav-link" href="{% url 'lottery:buy-ticket' %}">Buy Ticket</a>
                {% endif %}

                {% if request.path == "/bets/" %}
                    <a class="nav-link active" href="{% url 'lottery:bet-list' %}">Bets</a>
                {% else %}
                    <a class="nav-link" href="{% url 'lottery:bet-list' %}">Bets</a>
                {% endif %}

                {% if request.path == "/lotteries/" %}
                    <a class="nav-link active" href="{% url 'lottery:lottery-list' %}">Lotteries</a>
                {% else %}
                    <a class="nav-link" href="{% url 'lottery:lottery-list' %}">Lotteries</a>
                {% endif %}

                {% if request.path == "/schedule/" %}
                    <a class="nav-link active" href="{% url 'lottery:schedule' %}">Schedule</a>
                {% else %}
                    <a class="nav-link" href="{% url 'lottery:schedule' %}">Schedule</a>
                {% endif %}
                
                {% if request.path == "/faq/" %}
                    <a class="nav-link active" href="{% url 'lottery:faq' %}">FAQ</a>
                {% else %}
                    <a class="nav-link" href="{% url 'lottery:faq' %}">FAQ</a>
                {% endif %}

                {% if request.path == "/about/" %}
                    <a class="nav-link active" href="{% url 'lottery:about' %}">About</a>
                {% else %}
                    <a class="nav-link" href="{% url 'lottery:about' %}">About</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>