src/lottery/urls.py
from django.urls import path

from lottery.views.home import HomeView
from lottery.views.tickets import (
    AcceptBuyTicketNotice, BuyTicketView)
from lottery.views.bets import BetsListView
from lottery.views.lotteries import (
    LotteryListView, LotteryDetailView)
from lottery.views.about import AboutView
from lottery.views.schedule import ScheduleView
from lottery.views.faq import FAQView

app_name = 'lottery'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('buy-ticket/', BuyTicketView.as_view(), name='buy-ticket'),
    path('accept-buy-ticket-notice/', AcceptBuyTicketNotice.as_view(), name='accept-notice'),
    path('bets/', BetsListView.as_view(), name='bet-list'),
    path('lotteries/', LotteryListView.as_view(), name='lottery-list'),
    path('lotteries/<int:pk>/', LotteryDetailView.as_view(), name='lottery-detail'),
    path('schedule/', ScheduleView.as_view(), name='schedule'),
    path('faq/', FAQView.as_view(), name='faq'),
    path('about/', AboutView.as_view(), name='about')
]

src/luckyfive/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('lottery.urls')),
    path('admin/', admin.site.urls),
]

src/lottery/models.py
from datetime import datetime, timezone
from django.db import models
from django.contrib.postgres.fields import (
    ArrayField)


class Lottery(models.Model):
    # Determins if the particular lottery is active or not
    # True means that it is the current ongoing lottery
    # There should be only one active lottery object
    is_active = models.BooleanField(default=True)

    # The lottery draw date (Sunday 09:00 UTC)
    draw_date = models.DateTimeField()

    # The policy ID that will be used to mint 
    # the tickets in this lottery
    policy_id = models.CharField(max_length=250)

    # The random.org api response
    api_response = models.JSONField(
        null=True,
        blank=True)

    date_created = models.DateTimeField(
        auto_now_add=True)

    # Determines the sequence of the lottery object
    seq = models.PositiveIntegerField(
        default=0,
        unique=True)

    def __str__(self):
        seq = 'Lottery ' + str(self.seq)
        formatted_date = self.draw_date.strftime(
            '%B %d, %Y %H:%M %Z')
        return seq + ' - ' + formatted_date

    @property
    def lucky_five(self):
        if self.api_response:
            return self.api_response.get(
                'result').get('random').get(
                'data')[0]
        return None

    @property
    def bets(self):
        return self.bet_set.all()

    @property
    def active_bets(self):
        return self.bet_set.filter(
            is_active=True,
            is_paid=True)

    @property
    def winners(self):
        return self.lotterywinner_set.all()

    def get_current_lottery():
        now = datetime.now(timezone.utc)
        current = Lottery.objects.filter(
            is_active=True,
            draw_date__gte=now).last()
        return current

    def is_ticket_sale_schedule():
        pass


class Bet(models.Model):
  	# The bettor's lucky-five number
    lucky_five = ArrayField(
        models.PositiveIntegerField(),
        size=5)

    # The address where the bettor will send ADA to
    payment_address = models.CharField(max_length=250)

    # The bettor's UTXO where the ticket-nft was sent
    bettor = models.CharField(
        max_length=250,
        null=True,
        blank=True)

    # The status of the bettor's bet if the ticket nft
    # is already minted
    is_active = models.BooleanField(default=False)

    # The status of the bettor's bet after checking if
    # he/she actually sent the ADA
    is_paid = models.BooleanField(default=False)

    # The lottery this bet is tied to
    lottery = models.ForeignKey(
        Lottery,
        null=True,
        on_delete=models.SET_NULL)

    # The ticket-nft assetID
    ticket = models.CharField(
        max_length=250,
        null=True,
        blank=True)

    def __str__(self):
        return str(self.lucky_five)


class LotteryWinner(models.Model):
    lottery = models.ForeignKey(
        Lottery,
        on_delete=models.CASCADE)

    # The bet of the winner
    bet = models.ForeignKey(
        Bet,
        on_delete=models.CASCADE)

    # Determines if the winner is paid or not
    is_fulfilled = models.BooleanField(
        default=False)

    # The transaction ID of the prize payment
    tx_id = models.CharField(
        max_length=250,
        null=True,
        blank=True)

    def __str__(self):
        return str(self.bet)

src/lottery/views.py
from datetime import datetime, timezone, timedelta

from django.shortcuts import render
from django.views import View


class HomeView(View):
    template_name = 'lottery/homepage.html'

    def get(self, request, *args, **kwargs):
        # Get today in UTC
        # now_utc = datetime.now(timezone.utc)
        now_utc = datetime(2021, 11, 29, 9, 0, 0, 0, timezone.utc)
        print('Current date: ', now_utc)

        # Check if today is lottery day
        # Sunday 09:00 UTC - Monday 08:59 UTC
        weekday = now_utc.weekday()
        hour = now_utc.hour
        is_lottery = False

        if weekday == 6 or weekday == 0: #0-6, monday-sunday
            if weekday == 6 and hour >= 9:
                is_lottery = True
            elif weekday == 0 and hour < 9:
                is_lottery = True

        if is_lottery:
            # if lottery day, query result
            print("IT IS LOTTERY DAY!")
            pass

        else:
            # else get next lottery date in UTC (Sunday 09:00 UTC)
            offset = 6 - weekday
            next_lottery = now_utc + timedelta(days=offset)
            next_lottery = datetime(
                next_lottery.year, next_lottery.month, next_lottery.day,
                hour=9, minute=0,
                second=0, microsecond=0,
                tzinfo=timezone.utc
            )
            print('Next lottery is: ', next_lottery)

            # return date and create countdown timer in the frontend

        return render(request, self.template_name, {})


class BuyTicketView(View):
    template_name = 'lottery/buyticket.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})

src/lottery/views/about.py
from django.shortcuts import render
from django.views import View


class AboutView(View):
    template_name = 'lottery/about.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})

src/lottery/views/bets.py
from django.shortcuts import (
    render, get_object_or_404)
from django.views import View
from django.views.generic import ListView

from lottery.models import Bet, Lottery


class BetsListView(ListView):
    paginate_by = 10
    ordering = 'pk'
    queryset = Bet.objects.all()
    template_name = 'lottery/bet_list.html'

    def get_queryset(self, lottery):
        queryset = self.queryset
        queryset = lottery.active_bets

        ordering = self.ordering
        if ordering:
            if isinstance(ordering, str):
                ordering = (ordering,)
            queryset = queryset.order_by(*ordering)

        return queryset

    def get(self, request, *args, **kwargs):
        context = {}

        try:
            lottery = None
            lottery_seq = self.request.GET.get(
                'lottery')

            if lottery_seq:
                if lottery_seq.isdigit():
                    lottery = get_object_or_404(
                        Lottery, seq=int(lottery_seq))
                else:
                    raise Exception('Opps. Lottery not found.')
            else:
                lottery = Lottery.get_current_lottery()

            if lottery is None:
                raise Exception('No active lottery today.')

            self.object_list = self.get_queryset(lottery)
            allow_empty = self.get_allow_empty()

            if not allow_empty:
                # When pagination is enabled and object_list is a queryset,
                # it's better to do a cheap query than to load the unpaginated
                # queryset in memory.
                if self.get_paginate_by(self.object_list) is not None and hasattr(self.object_list, 'exists'):
                    is_empty = not self.object_list.exists()
                else:
                    is_empty = not self.object_list
                if is_empty:
                    raise Http404(_('Empty list and “%(class_name)s.allow_empty” is False.') % {
                        'class_name': self.__class__.__name__,
                    })
            context = self.get_context_data()
            context['lottery'] = lottery

            return self.render_to_response(context)

        except Exception as e:
            context = {'error': str(e)}

        return render(request, self.template_name, context)

src/lottery/views/faq.py
from django.shortcuts import render
from django.views import View


class FAQView(View):
    template_name = 'lottery/faq.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})

src/lottery/views/home.py
from django.shortcuts import render
from django.views import View
from lottery.models import Lottery


class HomeView(View):
    template_name = 'lottery/home.html'

    def get(self, request, *args, **kwargs):
        # Get current lottery
        lottery = Lottery.objects.last()

        context = {
            'lottery': lottery
        }

        return render(request, self.template_name, context)

src/lottery/views/lotteries.py
from django.shortcuts import render
from django.views import View
from django.views.generic import (
    DetailView, ListView)

from lottery.models import Lottery


class LotteryListView(ListView):
    paginate_by = 9
    ordering = '-seq'
    queryset = Lottery.objects.all()


class LotteryDetailView(DetailView):
    queryset = Lottery.objects.all()

src/lottery/views/results.py
from django.shortcuts import render
from django.views import View

from lottery.models import Lottery

class ResultsView(View):
    template_name = 'lottery/results.html'

    def get(self, request, *args, **kwargs):
        lotteries = Lottery.objects.filter(
            is_active=False)

        context = {
            'lotteries': lotteries
        }
        return render(request, self.template_name, context)

src/lottery/views/schedule.py
from django.shortcuts import render
from django.views import View


class ScheduleView(View):
    template_name = 'lottery/schedule.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})

src/lottery/views/tickets.py
from django.shortcuts import render
from django.views import View
from django.http import JsonResponse

from lottery.models import Lottery
from lottery.cardano.operations import (
    generate_payment_address)


class AcceptBuyTicketNotice(View):

    def get(self, request, *args, **kwargs):
        try:
            if request.is_ajax():
                wallet_check = self.request.GET.get('walletCheck')
                terms_check = self.request.GET.get('termsCheck')

                if not (wallet_check == 'true' and terms_check == 'true'):
                    raise Exception('You must accept all terms and conditions.')

                data = {
                    'payment_address': generate_payment_address(),
                    'status_code': 200
                }

                return JsonResponse(data)

            raise Exception('Unable to process request.')

        except Exception as e:
            data = {
                'message': str(e),
                'status_code': 500
            }
            return JsonResponse(data)


class BuyTicketView(View):
    template_name = 'lottery/buy_ticket.html'

    def get(self, request, *args, **kwargs):
        current_lottery = Lottery.get_current_lottery()

        context = {
            'current_lottery': current_lottery
        }
        return render(request, self.template_name, context)

src/lottery/templates/lottery/about.html
{% extends 'base.html' %}

{% block content %}
	<h1>ABOUT</h1>
{% endblock %}

src/lottery/templates/lottery/bet_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container-fluid" align="center">
        {% if error %}
            <div class="card border-danger error-card">
                <div class="card-body">
                    <h1><i class="bi bi-x-circle"></i></h1>
                    <h2>{{ error }}</h2>
                    {% if error == "No active lottery today." %}
                        <p>
                            <a href="{% url 'lottery:lottery-list' %}">
                            Browse through the previous bets</a> or
                            see the <a href="{% url 'lottery:schedule' %}">
                            next lottery schedule</a>.
                        </p>
                    {% endif %}
                </div>
            </div>
        {% elif object_list %}
            <div class="table-responsive bets-table">
                <table class="table table-bordered table-sm table-hover caption-top">
                    <caption>
                        <a
                            href="{% url 'lottery:lottery-detail' lottery.pk %}"
                            class="link-dark"
                        >
                            {{ lottery }}
                            <span class="badge bg-secondary">
                                {{ object_list.count }} bets
                            </span>
                        </a>
                    </caption>
                    <thead class="table-dark" align="center">
                        <tr>
                            <th>Bettor</th>
                            <th>LuckyFive</th>
                            <th>Ticket</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for bet in object_list %}
                        <tr>
                            <td>{{ bet.bettor }}</td>
                            <td>{{ bet.lucky_five }}</td>
                            <td>{{ bet.ticket }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        {% else %}
            <h1><i class="bi bi-x-circle"></i></h1>
            <h2>0 bets found.</h2>
            <p class="text-muted">{{ lottery }}</p>
        {% endif %}
    </div>

{% endblock %}

src/lottery/templates/lottery/bets.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container-fluid" align="center">
        <div class="table-responsive bets-table">
            <table class="table table-bordered table-sm table-hover caption-top">
                <caption>Current Lottery: {{ lottery }}</caption>
                <thead class="table-dark" align="center">
                    <tr>
                        <th>Bettor</th>
                        <th>LuckyFive</th>
                        <th>Ticket</th>
                    </tr>
                </thead>
                <tbody>
                    {% for bet in lottery.active_bets %}
                    <tr>
                        <td>{{ bet.bettor }}</td>
                        <td>{{ bet.lucky_five }}</td>
                        <td>{{ bet.ticket }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

src/lottery/templates/lottery/buy_ticket.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    {% if current_lottery %}
        <div class="container-fluid buy-ticket-container mb-5" id="buyTicketContainer">
            <div class="card">
                <div class="card-body" id="cardBody">
                    <div class="mb-3 form-check">
                        <input type="checkbox" class="form-check-input" id="walletCheck">
                        <label class="form-check-label" for="walletCheck">
                            I am not sending from an exchange. I am using a cardano
                            native wallet that supports NFTs (e.g. Daedalus, Yoroi, Nami)
                        </label>
                    </div>
                    <div class="mb-3 form-check">
                        <input type="checkbox" class="form-check-input" id="termsCheck">
                        <label class="form-check-label" for="termsCheck">
                            I have read and agreed to the <a href="#">terms and conditions</a>.
                        </label>
                    </div>
                    <div id="alert"></div>
                    <div class="continue-button" align="end" id="acceptBuyTicketNotice">
                        <button class="btn btn-primary">
                            Continue
                        </button>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <div class="container-fluid" align="center">
            <div class="card border-danger error-card">
                <div class="card-body">
                    <h1><i class="bi bi-emoji-frown"></i></h1>
                    <h2>Ticket booth is closed.</h2>
                    <p>
                        You can't buy a ticket right now since the ticket booth is closed.<br>
                        Visit the <a href="{% url 'lottery:schedule' %}">lottery schedule page</a>
                        to see when can you start buying tickets.
                    </p>
                </div>
            </div>
        </div>
    {% endif %}

{% endblock %}


{% block script %}
    <script type="text/javascript">

        $(document).ready(function() {
            $("#acceptBuyTicketNotice").click(function() {
                var walletCheck = document.getElementById("walletCheck").checked;
                var termsCheck = document.getElementById("termsCheck").checked;
                var $cardBody = $("#cardBody");
                var $alert = $("#alert");
                $alert.empty();

                if (!walletCheck || !termsCheck) {
                    $alert.append(
                        '<div class="alert alert-danger mb-3" role="alert">' +
                        'Please agree to all terms and conditions.</div>');
                } else {
                    $.ajax({
                        url: `{% url 'lottery:accept-notice' %}`,
                        data: {
                            walletCheck: walletCheck,
                            termsCheck: termsCheck
                        },
                        success: function (response) {
                            if (response.status_code == 200) {
                                $cardBody.empty();
                                console.log(response)

                                let paymentAddress = '<div class="mb-4"><h5>Please send 5 ADA to this address:</h5><div style="background-color: gray; padding: 20px; color: white; border-radius:10px;">' + response.payment_address + '</div>';

                                let luckfive = '<div class="mb-3"><label for="luckyFive" class="form-label h5">Your LuckyFive number:</label><input type="number" class="form-control" id="luckyFive"></div>';

                                let button = '<div class="continue-button" align="end"><button class="btn btn-primary">Continue</button></div>';

                                $cardBody.append([paymentAddress, luckfive, button]);

                            } else {
                                let message = '<div class="alert alert-danger mb-3" role="alert">' +
                                    response.message + '</div>';
                                $alert.append(message);
                            }
                        },
                        dataType: "json"
                    });
                }
            });
        });
    </script>
{% endblock %}

src/lottery/templates/lottery/buyticket.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container-fluid" align="center">
        <h1>Buy ticket</h1>
    </div>

{% endblock %}

src/lottery/templates/lottery/countdown_timer.html
<div class="container-fluid content">
    <h4>countdown timer</h4>
</div>

src/lottery/templates/lottery/faq.html
{% extends 'base.html' %}

{% block content %}
	<h1>FAO</h1>
{% endblock %}

src/lottery/templates/lottery/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container-fluid">
        {% if lottery.is_active %}
            <h3>Active Lottery</h3>
            <p>Lottery draw_date: {{ lottery }}</p>
        {% else %}
            <h3>Lottery Result</h3>
            <ul>
                <li>Drawn: {{ lottery }}</li>
                <li>LuckyFive: {{ lottery.lucky_five }}</li>
                <li>Winners: {{ lottery.winners.count }}</li>
            </ul>
        {% endif %}
    </div>

{% endblock %}

src/lottery/templates/lottery/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="container-fluid">
        {% if lottery.is_active %}
            <h3>Active Lottery</h3>
            <p>Lottery draw_date: {{ lottery }}</p>
        {% else %}
            <h3>Lottery Result</h3>
            <ul>
                <li>Drawn: {{ lottery }}</li>
                <li>LuckyFive: {{ lottery.lucky_five }}</li>
                <li>Winners: {{ lottery.winners }}</li>
            </ul>
        {% endif %}
    </div>

{% endblock %}

src/lottery/templates/lottery/lottery_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    
    <div class="container-fluid">
        {{ object }}
    </div>
    
{% endblock %}

src/lottery/templates/lottery/lottery_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    
    <div class="container-fluid">
        <div class="row row-cols-1 row-cols-md-3 g-4 lottery-list">
        {% for lottery in object_list %}
            <div class="col">
                <div class="card h-100">
                    <div class="card-header">
                        <h5>
                            <a
                                class="link-dark"
                                href="{% url 'lottery:lottery-detail' lottery.pk %}"
                            >
                                {{ lottery }}
                            </a>
                        </h5>
                    </div>
                    <div class="card-body" align="center">
                        {% if lottery.lucky_five %}
                            <p class="fs-1 fw-bold">{{ lottery.lucky_five }}</p>
                        {% else %}
                            <p class="fs-1 fw-bold">active</p>
                        {% endif %}
                        <div class="row">
                            <div class="col">
                                <a href="{% url 'lottery:bet-list' %}?lottery={{ lottery.seq }}">
                                    {{ lottery.active_bets.count }} Bets
                                </a>
                            </div>
                            <div class="col">
                                {{ lottery.winners.count }} Winners
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>

{% endblock %}

src/lottery/templates/lottery/results.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    
    <div class="container-fluid">
        <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for lottery in lotteries %}
            <div class="col">
                <div class="card h-100">
                    <div class="card-header">
                        {{ lottery }}
                    </div>
                    <div class="card-body" align="center">
                        <p class="fs-1 fw-bold">12312</p>
                        <div class="row">
                            <div class="col">
                                {{ lottery.active_bets.count }} bets
                            </div>
                            <div class="col">
                                {{ lottery.winners.count }} Winners
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
    

{% endblock %}

src/lottery/templates/lottery/schedule.html
{% extends 'base.html' %}

{% block content %}

	<div class="container-fluid" align="center">
		<div class="card border-info schedule-card">
			<div class="card-header text-muted">
				Weekly Lottery Schedule
			</div>
			<div class="card-body">
				<div class="ticket-sale-schedule mb-5">
					<h4><i class="bi bi-ticket-perforated"></i> Ticket Sale:</h4>
					<h5 class="text-primary">Monday 09:00 UTC to Sat 17:00 UTC</h5>
				</div>
				<div class="result-schedule">
					<h4><i class="bi bi-megaphone"></i> Result Announcement:</h4>
					<h5 class="text-success">Every Sunday 09:00 UTC</h5>
				</div>
			</div>
		</div>
	</div>

{% endblock %}